### ISSUE TITLE
Sprint 1: Skills and Resources Audit

### ISSUE THREAD

**Issue by caitlynchan9** [caitlynchan9/CITS3200-Project#1]

**Comment by Andrew801** [comment]
Completed. Microsoft word copy available on google drive.

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
haraldwirdgeil, @baotinhoc, @ibiernacki, @theandym, @mmmy, @lemansVector2, @classicvalues, @arioboo, @marionetteliu, @DavidJNy, @billythekidz, @Aleksjjj11, @stevennt, @ralph427, @pittss, @AwesomeObserver, @jakkph, @endless-iterations, @shahar0409, @allenlooplee, @Barzaria, @Detroyer2222, @atul3077, @fullofcaffeine, @mablue, @mcweeds, @danii1, @tinybug, @Conight, @nisargshah95, @Matesensei, @wossig, @Aqua-4, @qaz734913414, @sharpleafage, @christiankywong, @cheadrian, @higty, @zzzzakhar, @nooooo380, @wvigiloliver, @has12zen, @SurabhiDivakar, @andude10, @iszfp, @jodadoj, @paavalan, @vipultanwr, @Aeolian-7, @gofullthrottleMuhammadRedwan, @szation, @merlijndetovenaar84, @Markorv, @mblkhr, @berensn, @yduan-ug, @mohan-mu, @pradeepss, @ChoiInYeol, @robinroyer, @junho7, @aShadow20, @mirikaz, @wlclass, @bailie720, @vincentyang116, @mintbird, @mohammadmaso, @nctechltd, @AndreevAlex, @immanuelrosal, @xaviergoby, @victorgrubio, @dangwenze, @EthanM242, @JOE1994, @Matx00, @Ericren2008, @dev-oq, @rafo, @nicolarohner1337, @AngusZHAN, @free-mx, @jgwill, @eugeneyng, @walterbelleville, @collinsmao, @strikerEng, @Tevenec, @joahn3, @nrvadlamudi, @roelofvkr, @samuelbushi, @azens, @DanielPhoton, @kevkmr, @Ubiquity888, @sqane, @saiKumarGanji
